server.modules = (
    "mod_cgi",
    "mod_rewrite"
)

server.document-root = "/usr/share/miniguard/html"
index-file.names     = ( "index.html" )
server.port          = 80
server.bind          = "0.0.0.0"

# CGI config
cgi.assign = ( ".sh" => "/bin/sh" )

# MIME types
mimetype.assign = (
    ".html" => "text/html",
    ".css"  => "text/css",
    ".json" => "application/json"
)

server.errorlog = "/var/log/lighttpd-error.log"
accesslog.filename = "/var/log/lighttpd-access.log"
